import { Component, EventEmitter, inject, Input, OnChanges, Output } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button'; import { MatCardModule } from '@angular/material/card'; import { MatCheckboxModule } from '@angular/material/checkbox'; import { MatFormFieldModule } from '@angular/material/form-field'; import { MatInputModule } from '@angular/material/input'; import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { finalize } from 'rxjs'; import { AuthService, AuthUser, CompetitionKey } from '../../services/auth.service';

const OPTIONS: Array<{ value: CompetitionKey; label: string }> = [
  { value:'LEC',label:'LEC (tous les splits)' }, { value:'LCK',label:'LCK (tous les splits)' }, { value:'LCS',label:'LCS (tous les splits)' }, { value:'LPL',label:'LPL (tous les splits)' }, { value:'MSI',label:'MSI' }, { value:'FIRST_STAND',label:'First Stand' }, { value:'WORLDS',label:'Worlds' },
];
@Component({ selector:'app-profile-tab', standalone:true, imports:[ReactiveFormsModule,MatButtonModule,MatCardModule,MatCheckboxModule,MatFormFieldModule,MatInputModule,MatSnackBarModule],
 template:`<mat-card appearance="outlined"><mat-card-header><mat-card-subtitle>Mon profil</mat-card-subtitle><mat-card-title>Compétitions suivies</mat-card-title></mat-card-header><mat-card-content><p>Une compétition régionale inclut automatiquement tous ses splits et playoffs.</p>
 <mat-form-field appearance="outline" subscriptSizing="dynamic"><mat-label>Rechercher une compétition</mat-label><input matInput type="search" [formControl]="search" placeholder="LEC, LCK, Worlds…"></mat-form-field>
 <div class="checklist">@for (competition of filteredOptions(); track competition.value) { <mat-checkbox [checked]="selected.value.includes(competition.value)" (change)="toggle(competition.value,$event.checked)">{{ competition.label }}</mat-checkbox> } @empty { <p>Aucune compétition trouvée.</p> }</div>
 <div class="actions"><button mat-flat-button type="button" (click)="save()" [disabled]="saving">{{ saving ? 'Enregistrement…' : 'Enregistrer' }}</button></div></mat-card-content></mat-card>`,
 styles:[`mat-card-header{margin-bottom:4px} p{color:var(--mat-sys-on-surface-variant)} mat-form-field{width:100%}.checklist{border:1px solid var(--mat-sys-outline-variant);border-radius:14px;display:grid;gap:4px;grid-template-columns:repeat(2,minmax(0,1fr));padding:10px}.checklist mat-checkbox{padding:4px 8px}.actions{display:flex;justify-content:flex-end;margin-top:14px}@media(max-width:680px){.checklist{grid-template-columns:1fr}}`], })
export class ProfileTabComponent implements OnChanges { private readonly auth=inject(AuthService); private readonly snack=inject(MatSnackBar); @Input({required:true}) user!:AuthUser; @Output() readonly saved=new EventEmitter<void>(); readonly search=new FormControl('',{nonNullable:true}); readonly selected=new FormControl<CompetitionKey[]>([],{nonNullable:true}); saving=false;
 ngOnChanges(){ this.selected.setValue(this.user.favoriteCompetitions,{emitEvent:false}); } filteredOptions(){const q=this.search.value.trim().toLowerCase();return q?OPTIONS.filter(x=>x.label.toLowerCase().includes(q)):OPTIONS;} toggle(key:CompetitionKey,on:boolean){const values=new Set(this.selected.value);if(on)values.add(key);else values.delete(key);this.selected.setValue([...values]);}
 save(){this.saving=true;this.auth.updateFavoriteCompetitions(this.selected.value).pipe(finalize(()=>this.saving=false)).subscribe({next:()=>{this.snack.open('Compétitions favorites enregistrées !','Fermer',{duration:3000});this.saved.emit();},error:()=>this.snack.open("Les favoris n'ont pas pu être enregistrés.",'Fermer',{duration:4000})});}}
