import { BadRequestException, NotFoundException } from '@nestjs/common'; import { describe,expect,it,vi } from 'vitest'; import { EsportsService } from './esports.service';
const teams=[{id:'a',name:'A',code:'A',logoColor:'#000'},{id:'b',name:'B',code:'B',logoColor:'#111'}];
const match=(extra={})=>({id:'m1',league:'LEC',tournament:'Spring',startsAt:new Date(),format:'BO3',status:'upcoming',teams,winnerId:null,scoreA:null,scoreB:null,syncedAt:new Date(),updatedAt:new Date(),...extra});
function setup(){const prisma={match:{findMany:vi.fn(),findUnique:vi.fn()},prediction:{findMany:vi.fn(),upsert:vi.fn()}};return{prisma,service:new EsportsService(prisma as never)};}
describe('EsportsService',()=>{
 it('orders and maps matches',async()=>{const{service,prisma}=setup();prisma.match.findMany.mockResolvedValue([match()]);const result=await service.getMatches();expect(prisma.match.findMany).toHaveBeenCalledWith({orderBy:{startsAt:'asc'}});expect(result[0].teams).toEqual(teams);});
 it('rejects missing, closed and invalid predictions',async()=>{const{service,prisma}=setup();prisma.match.findUnique.mockResolvedValue(null);await expect(service.createPrediction({matchId:'x',playerName:'x',score:[2,1]},'Leo')).rejects.toBeInstanceOf(NotFoundException);prisma.match.findUnique.mockResolvedValue(match({status:'live'}));await expect(service.createPrediction({matchId:'m1',playerName:'x',score:[2,1]},'Leo')).rejects.toBeInstanceOf(BadRequestException);prisma.match.findUnique.mockResolvedValue(match());await expect(service.createPrediction({matchId:'m1',playerName:'x',score:[1,1]},'Leo')).rejects.toBeInstanceOf(BadRequestException);});
 it('upserts under the authenticated name',async()=>{const{service,prisma}=setup();prisma.match.findUnique.mockResolvedValue(match());prisma.prediction.upsert.mockResolvedValue({id:'p',matchId:'m1',playerName:'Leo',winnerId:'a',scoreA:2,scoreB:1,createdAt:new Date(),points:0});const result=await service.createPrediction({matchId:'m1',playerName:'Hacker',score:[2,1]},'Leo');expect(prisma.prediction.upsert).toHaveBeenCalledWith(expect.objectContaining({create:expect.objectContaining({playerName:'Leo',winnerId:'a'})}));expect(result.playerName).toBe('Leo');});
 it('aggregates and sorts the leaderboard',async()=>{const{service,prisma}=setup();prisma.prediction.findMany.mockResolvedValue([{id:'1',matchId:'m',playerName:'A',winnerId:'x',scoreA:1,scoreB:0,createdAt:new Date(),points:3},{id:'2',matchId:'m',playerName:'B',winnerId:'x',scoreA:1,scoreB:0,createdAt:new Date(),points:5}]);expect((await service.getLeaderboard()).map(x=>x.playerName)).toEqual(['B','A']);});
});
